project:
  type: website

website:
  title: "IS608 - Group 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Proposal.qmd
        text: Proposal
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

